require:
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 2.6.2
  TargetRailsVersion: 5.2.2
  # Cop names are not d§splayed in offense messages by default. Change behavior
  # by overriding DisplayCopNames, or by giving the -D/--display-cop-names
  # option.
  DisplayCopNames: true
  # Style guide URLs are not displayed in offense messages by default. Change
  # behavior by overriding DisplayStyleGuide, or by giving the
  # -S/--display-style-guide option.
  DisplayStyleGuide: true
  # Exclude some files
  Exclude:
    - 'vendor/**/*'
    - 'db/migrate/**/*'
    - 'db/schema.rb'
    - 'tmp/**/*'
    - 'bin/**/*'
    - 'config/**/*'

# This cop is aimed at large block in the imperative programming sense
# Tests are declarative
Metrics/BlockLength:
  Exclude:
    - spec/**/*
Metrics/MethodLength:
  Max: 30
Metrics/AbcSize:
  Max: 30

Naming/AccessorMethodName:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false
# WTF??
Style/SymbolProc:
  Enabled: false