version: '3'
services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
  web:
    build: .
    stdin_open: true
    tty: true
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/egsl-website-api
    ports:
      - "3000:3000"
      - "1025:1025"
      - "1080:1080"
    depends_on:
      - db
  hooks:
    build:
      context: .
      dockerfile: 'Dockerfile.githooks'
    volumes:
      - ./.git:/tmp/.git
      - ./hooks:/tmp/hooks
  swagger:
    image: swaggerapi/swagger-ui
    ports:
      - "3030:8080"
    volumes:
      - ./swagger-ui/swagger.yml:/usr/share/nginx/html/swagger.yml

